vsftpd = "/etc/ftpusers
/etc/init.d/vsftpd
/etc/init/vsftpd.conf
/etc/logrotate.d/vsftpd
/etc/pam.d/vsftpd
/etc/systemd/system/vsftpd.service
/etc/vsftpd.conf
/usr/sbin/vsftpd
/usr/share/apport/package-hooks/vsftpd.py
/usr/share/doc/vsftpd/AUDIT
/usr/share/doc/vsftpd/BENCHMARKS
/usr/share/doc/vsftpd/BUGS
/usr/share/doc/vsftpd/FAQ.gz
/usr/share/doc/vsftpd/NEWS.Debian.gz
/usr/share/doc/vsftpd/README
/usr/share/doc/vsftpd/README.Debian
/usr/share/doc/vsftpd/README.security
/usr/share/doc/vsftpd/README.ssl
/usr/share/doc/vsftpd/REWARD
/usr/share/doc/vsftpd/SECURITY/DESIGN.gz
/usr/share/doc/vsftpd/SECURITY/IMPLEMENTATION
/usr/share/doc/vsftpd/SECURITY/OVERVIEW
/usr/share/doc/vsftpd/SECURITY/TRUST.gz
/usr/share/doc/vsftpd/SIZE
/usr/share/doc/vsftpd/SPEED
/usr/share/doc/vsftpd/TODO
/usr/share/doc/vsftpd/TUNING
/usr/share/doc/vsftpd/changelog.Debian.gz
/usr/share/doc/vsftpd/copyright
/usr/share/doc/vsftpd/examples/INTERNET_SITE/README.gz
/usr/share/doc/vsftpd/examples/INTERNET_SITE/vsftpd.conf
/usr/share/doc/vsftpd/examples/INTERNET_SITE/vsftpd.xinetd
/usr/share/doc/vsftpd/examples/INTERNET_SITE_NOINETD/README
/usr/share/doc/vsftpd/examples/INTERNET_SITE_NOINETD/vsftpd.conf
/usr/share/doc/vsftpd/examples/PER_IP_CONFIG/README
/usr/share/doc/vsftpd/examples/PER_IP_CONFIG/hosts.allow
/usr/share/doc/vsftpd/examples/README
/usr/share/doc/vsftpd/examples/VIRTUAL_HOSTS/README
/usr/share/doc/vsftpd/examples/VIRTUAL_USERS/README.gz
/usr/share/doc/vsftpd/examples/VIRTUAL_USERS/logins.txt
/usr/share/doc/vsftpd/examples/VIRTUAL_USERS/vsftpd.conf
/usr/share/doc/vsftpd/examples/VIRTUAL_USERS/vsftpd.pam
/usr/share/doc/vsftpd/examples/VIRTUAL_USERS_2/README
/usr/share/man/man5/vsftpd.conf.5.gz
/usr/share/man/man8/vsftpd.8.gz"

apache = "/etc/apache2/apache2.conf
/etc/apache2/conf-available/charset.conf
/etc/apache2/conf-available/localized-error-pages.conf
/etc/apache2/conf-available/other-vhosts-access-log.conf
/etc/apache2/conf-available/security.conf
/etc/apache2/conf-available/serve-cgi-bin.conf
/etc/apache2/envvars
/etc/apache2/magic
/etc/apache2/mods-available/access_compat.load
/etc/apache2/mods-available/actions.conf
/etc/apache2/mods-available/actions.load
/etc/apache2/mods-available/alias.conf
/etc/apache2/mods-available/alias.load
/etc/apache2/mods-available/allowmethods.load
/etc/apache2/mods-available/asis.load
/etc/apache2/mods-available/auth_basic.load
/etc/apache2/mods-available/auth_digest.load
/etc/apache2/mods-available/auth_form.load
/etc/apache2/mods-available/authn_anon.load
/etc/apache2/mods-available/authn_core.load
/etc/apache2/mods-available/authn_dbd.load
/etc/apache2/mods-available/authn_dbm.load
/etc/apache2/mods-available/authn_file.load
/etc/apache2/mods-available/authn_socache.load
/etc/apache2/mods-available/authnz_ldap.load
/etc/apache2/mods-available/authz_core.load
/etc/apache2/mods-available/authz_dbd.load
/etc/apache2/mods-available/authz_dbm.load
/etc/apache2/mods-available/authz_groupfile.load
/etc/apache2/mods-available/authz_host.load
/etc/apache2/mods-available/authz_owner.load
/etc/apache2/mods-available/authz_user.load
/etc/apache2/mods-available/autoindex.conf
/etc/apache2/mods-available/autoindex.load
/etc/apache2/mods-available/buffer.load
/etc/apache2/mods-available/cache.load
/etc/apache2/mods-available/cache_disk.conf
/etc/apache2/mods-available/cache_disk.load
/etc/apache2/mods-available/cache_socache.load
/etc/apache2/mods-available/cgi.load
/etc/apache2/mods-available/cgid.conf
/etc/apache2/mods-available/cgid.load
/etc/apache2/mods-available/charset_lite.load
/etc/apache2/mods-available/data.load
/etc/apache2/mods-available/dav.load
/etc/apache2/mods-available/dav_fs.conf
/etc/apache2/mods-available/dav_fs.load
/etc/apache2/mods-available/dav_lock.load
/etc/apache2/mods-available/dbd.load
/etc/apache2/mods-available/deflate.conf
/etc/apache2/mods-available/deflate.load
/etc/apache2/mods-available/dialup.load
/etc/apache2/mods-available/dir.conf
/etc/apache2/mods-available/dir.load
/etc/apache2/mods-available/dump_io.load
/etc/apache2/mods-available/echo.load
/etc/apache2/mods-available/env.load
/etc/apache2/mods-available/expires.load
/etc/apache2/mods-available/ext_filter.load
/etc/apache2/mods-available/file_cache.load
/etc/apache2/mods-available/filter.load
/etc/apache2/mods-available/headers.load
/etc/apache2/mods-available/heartbeat.load
/etc/apache2/mods-available/heartmonitor.load
/etc/apache2/mods-available/include.load
/etc/apache2/mods-available/info.conf
/etc/apache2/mods-available/info.load
/etc/apache2/mods-available/lbmethod_bybusyness.load
/etc/apache2/mods-available/lbmethod_byrequests.load
/etc/apache2/mods-available/lbmethod_bytraffic.load
/etc/apache2/mods-available/lbmethod_heartbeat.load
/etc/apache2/mods-available/ldap.conf
/etc/apache2/mods-available/ldap.load
/etc/apache2/mods-available/log_debug.load
/etc/apache2/mods-available/log_forensic.load
/etc/apache2/mods-available/lua.load
/etc/apache2/mods-available/macro.load
/etc/apache2/mods-available/mime.conf
/etc/apache2/mods-available/mime.load
/etc/apache2/mods-available/mime_magic.conf
/etc/apache2/mods-available/mime_magic.load
/etc/apache2/mods-available/mpm_event.conf
/etc/apache2/mods-available/mpm_event.load
/etc/apache2/mods-available/mpm_prefork.conf
/etc/apache2/mods-available/mpm_prefork.load
/etc/apache2/mods-available/mpm_worker.conf
/etc/apache2/mods-available/mpm_worker.load
/etc/apache2/mods-available/negotiation.conf
/etc/apache2/mods-available/negotiation.load
/etc/apache2/mods-available/proxy.conf
/etc/apache2/mods-available/proxy.load
/etc/apache2/mods-available/proxy_ajp.load
/etc/apache2/mods-available/proxy_balancer.conf
/etc/apache2/mods-available/proxy_balancer.load
/etc/apache2/mods-available/proxy_connect.load
/etc/apache2/mods-available/proxy_express.load
/etc/apache2/mods-available/proxy_fcgi.load
/etc/apache2/mods-available/proxy_fdpass.load
/etc/apache2/mods-available/proxy_ftp.conf
/etc/apache2/mods-available/proxy_ftp.load
/etc/apache2/mods-available/proxy_html.load
/etc/apache2/mods-available/proxy_http.load
/etc/apache2/mods-available/proxy_scgi.load
/etc/apache2/mods-available/proxy_wstunnel.load
/etc/apache2/mods-available/ratelimit.load
/etc/apache2/mods-available/reflector.load
/etc/apache2/mods-available/remoteip.load
/etc/apache2/mods-available/reqtimeout.conf
/etc/apache2/mods-available/reqtimeout.load
/etc/apache2/mods-available/request.load
/etc/apache2/mods-available/rewrite.load
/etc/apache2/mods-available/sed.load
/etc/apache2/mods-available/session.load
/etc/apache2/mods-available/session_cookie.load
/etc/apache2/mods-available/session_crypto.load
/etc/apache2/mods-available/session_dbd.load
/etc/apache2/mods-available/setenvif.conf
/etc/apache2/mods-available/setenvif.load
/etc/apache2/mods-available/slotmem_plain.load
/etc/apache2/mods-available/slotmem_shm.load
/etc/apache2/mods-available/socache_dbm.load
/etc/apache2/mods-available/socache_memcache.load
/etc/apache2/mods-available/socache_shmcb.load
/etc/apache2/mods-available/speling.load
/etc/apache2/mods-available/ssl.conf
/etc/apache2/mods-available/ssl.load
/etc/apache2/mods-available/status.conf
/etc/apache2/mods-available/status.load
/etc/apache2/mods-available/substitute.load
/etc/apache2/mods-available/suexec.load
/etc/apache2/mods-available/unique_id.load
/etc/apache2/mods-available/userdir.conf
/etc/apache2/mods-available/userdir.load
/etc/apache2/mods-available/usertrack.load
/etc/apache2/mods-available/vhost_alias.load
/etc/apache2/mods-available/xml2enc.load
/etc/apache2/ports.conf
/etc/apache2/sites-available/000-default.conf
/etc/apache2/sites-available/default-ssl.conf
/etc/bash_completion.d/apache2
/etc/cron.daily/apache2
/etc/default/apache2
/etc/init.d/apache2
/etc/logrotate.d/apache2
/etc/ufw/applications.d/apache2-utils.ufw.profile
/usr/sbin/a2disconf
/usr/sbin/a2dismod
/usr/sbin/a2dissite
/usr/sbin/a2enconf
/usr/sbin/a2enmod
/usr/sbin/a2ensite
/usr/sbin/a2query
/usr/sbin/apache2ctl
/usr/sbin/apachectl
/usr/share/apache2/apache2-maintscript-helper
/usr/share/apache2/ask-for-passphrase
/usr/share/bug/apache2/control
/usr/share/bug/apache2/script
/usr/share/doc/apache2/NEWS.Debian.gz
/usr/share/doc/apache2/PACKAGING.gz
/usr/share/doc/apache2/README.Debian.gz
/usr/share/doc/apache2/README.backtrace
/usr/share/doc/apache2/README.multiple-instances
/usr/share/doc/apache2/changelog.Debian.gz
/usr/share/doc/apache2/copyright
/usr/share/doc/apache2/examples/apache2.monit
/usr/share/doc/apache2/examples/secondary-init-script
/usr/share/doc/apache2/examples/setup-instance
/usr/share/doc/apache2/migrate-sites.pl
/usr/share/lintian/overrides/apache2
/usr/share/man/man1/a2query.1.gz
/usr/share/man/man8/a2disconf.8.gz
/usr/share/man/man8/a2dismod.8.gz
/usr/share/man/man8/a2dissite.8.gz
/usr/share/man/man8/a2enconf.8.gz
/usr/share/man/man8/a2enmod.8.gz
/usr/share/man/man8/a2ensite.8.gz
/usr/share/man/man8/apache2ctl.8.gz
/usr/share/man/man8/apachectl.8.gz"

samba = "/etc/cron.daily/samba
/etc/init.d/nmbd
/etc/init.d/samba
/etc/init.d/samba-ad-dc
/etc/init.d/smbd
/etc/init/nmbd.conf
/etc/init/reload-smbd.conf
/etc/init/samba-ad-dc.conf
/etc/init/smbd.conf
/etc/logrotate.d/samba
/etc/ufw/applications.d/samba
/usr/bin/eventlogadm
/usr/bin/oLschema2ldif
/usr/bin/pdbedit
/usr/bin/profiles
/usr/bin/sharesec
/usr/bin/smbcontrol
/usr/bin/smbstatus
/usr/bin/smbta-util
/usr/lib/i386-linux-gnu/samba/hdb/hdb_samba4.so
/usr/lib/i386-linux-gnu/samba/libHDB_SAMBA4.so.0
/usr/lib/i386-linux-gnu/samba/libdb-glue.so.0
/usr/lib/i386-linux-gnu/samba/libpac.so.0
/usr/lib/i386-linux-gnu/samba/process_model/onefork.so
/usr/lib/i386-linux-gnu/samba/process_model/prefork.so
/usr/lib/i386-linux-gnu/samba/process_model/standard.so
/usr/lib/i386-linux-gnu/samba/service/cldap.so
/usr/lib/i386-linux-gnu/samba/service/dcerpc.so
/usr/lib/i386-linux-gnu/samba/service/dns.so
/usr/lib/i386-linux-gnu/samba/service/dns_update.so
/usr/lib/i386-linux-gnu/samba/service/drepl.so
/usr/lib/i386-linux-gnu/samba/service/kcc.so
/usr/lib/i386-linux-gnu/samba/service/kdc.so
/usr/lib/i386-linux-gnu/samba/service/ldap.so
/usr/lib/i386-linux-gnu/samba/service/nbtd.so
/usr/lib/i386-linux-gnu/samba/service/ntp_signd.so
/usr/lib/i386-linux-gnu/samba/service/s3fs.so
/usr/lib/i386-linux-gnu/samba/service/smb.so
/usr/lib/i386-linux-gnu/samba/service/web.so
/usr/lib/i386-linux-gnu/samba/service/winbind.so
/usr/lib/i386-linux-gnu/samba/service/wrepl.so
/usr/lib/python2.7/dist-packages/samba/dckeytab.so
/usr/sbin/mksmbpasswd
/usr/sbin/nmbd
/usr/sbin/samba
/usr/sbin/samba_dnsupdate
/usr/sbin/samba_spnupdate
/usr/sbin/samba_upgradedns
/usr/sbin/smbd
/usr/share/doc/samba/NEWS.Debian.gz
/usr/share/doc/samba/README.Debian
/usr/share/doc/samba/TODO.Debian
/usr/share/doc/samba/changelog.Debian.gz
/usr/share/doc/samba/copyright
/usr/share/doc/samba/examples/LDAP/README
/usr/share/doc/samba/examples/LDAP/get_next_oid
/usr/share/doc/samba/examples/LDAP/ol-schema-migrate.pl.gz
/usr/share/doc/samba/examples/LDAP/samba-nds.schema.gz
/usr/share/doc/samba/examples/LDAP/samba-schema-FDS.ldif.gz
/usr/share/doc/samba/examples/LDAP/samba-schema-netscapeds5.x.README
/usr/share/doc/samba/examples/LDAP/samba-schema.IBMSecureWay
/usr/share/doc/samba/examples/LDAP/samba.ldif.gz
/usr/share/doc/samba/examples/LDAP/samba.schema.at.IBM-DS.gz
/usr/share/doc/samba/examples/LDAP/samba.schema.gz
/usr/share/doc/samba/examples/LDAP/samba.schema.oc.IBM-DS
/usr/share/lintian/overrides/samba
/usr/share/man/man1/log2pcap.1.gz
/usr/share/man/man1/oLschema2ldif.1.gz
/usr/share/man/man1/profiles.1.gz
/usr/share/man/man1/sharesec.1.gz
/usr/share/man/man1/smbcontrol.1.gz
/usr/share/man/man1/smbstatus.1.gz
/usr/share/man/man8/eventlogadm.8.gz
/usr/share/man/man8/mksmbpasswd.8.gz
/usr/share/man/man8/nmbd.8.gz
/usr/share/man/man8/pdbedit.8.gz
/usr/share/man/man8/samba.8.gz
/usr/share/man/man8/smbd.8.gz
/usr/share/man/man8/smbta-util.8.gz
/usr/share/samba/setup/DB_CONFIG
/usr/share/samba/setup/ad-schema/MS-AD_Schema_2K8_Attributes.txt
/usr/share/samba/setup/ad-schema/MS-AD_Schema_2K8_Classes.txt
/usr/share/samba/setup/ad-schema/MS-AD_Schema_2K8_R2_Attributes.txt
/usr/share/samba/setup/ad-schema/MS-AD_Schema_2K8_R2_Classes.txt
/usr/share/samba/setup/aggregate_schema.ldif
/usr/share/samba/setup/cn=replicator.ldif
/usr/share/samba/setup/cn=samba-admin.ldif
/usr/share/samba/setup/cn=samba.ldif
/usr/share/samba/setup/display-specifiers/DisplaySpecifiers-Win2k0.txt
/usr/share/samba/setup/display-specifiers/DisplaySpecifiers-Win2k3.txt
/usr/share/samba/setup/display-specifiers/DisplaySpecifiers-Win2k3R2.txt
/usr/share/samba/setup/display-specifiers/DisplaySpecifiers-Win2k8.txt
/usr/share/samba/setup/display-specifiers/DisplaySpecifiers-Win2k8R2.txt
/usr/share/samba/setup/dns_update_list
/usr/share/samba/setup/fedora-ds-init.ldif
/usr/share/samba/setup/fedorads-dna.ldif
/usr/share/samba/setup/fedorads-index.ldif
/usr/share/samba/setup/fedorads-linked-attributes.ldif
/usr/share/samba/setup/fedorads-pam.ldif
/usr/share/samba/setup/fedorads-partitions.ldif
/usr/share/samba/setup/fedorads-refint-add.ldif
/usr/share/samba/setup/fedorads-refint-delete.ldif
/usr/share/samba/setup/fedorads-samba.ldif
/usr/share/samba/setup/fedorads-sasl.ldif
/usr/share/samba/setup/fedorads.inf
/usr/share/samba/setup/idmap_init.ldif
/usr/share/samba/setup/krb5.conf
/usr/share/samba/setup/memberof.conf
/usr/share/samba/setup/mmr_serverids.conf
/usr/share/samba/setup/mmr_syncrepl.conf
/usr/share/samba/setup/modules.conf
/usr/share/samba/setup/named.conf
/usr/share/samba/setup/named.conf.dlz
/usr/share/samba/setup/named.conf.update
/usr/share/samba/setup/named.txt
/usr/share/samba/setup/olc_mmr.conf
/usr/share/samba/setup/olc_seed.ldif
/usr/share/samba/setup/olc_serverid.conf
/usr/share/samba/setup/olc_syncrepl.conf
/usr/share/samba/setup/olc_syncrepl_seed.conf
/usr/share/samba/setup/prefixMap.txt
/usr/share/samba/setup/provision.ldif
/usr/share/samba/setup/provision.reg
/usr/share/samba/setup/provision.zone
/usr/share/samba/setup/provision_basedn.ldif
/usr/share/samba/setup/provision_basedn_modify.ldif
/usr/share/samba/setup/provision_basedn_options.ldif
/usr/share/samba/setup/provision_basedn_references.ldif
/usr/share/samba/setup/provision_computers_add.ldif
/usr/share/samba/setup/provision_computers_modify.ldif
/usr/share/samba/setup/provision_configuration.ldif
/usr/share/samba/setup/provision_configuration_basedn.ldif
/usr/share/samba/setup/provision_configuration_modify.ldif
/usr/share/samba/setup/provision_configuration_references.ldif
/usr/share/samba/setup/provision_dns_accounts_add.ldif
/usr/share/samba/setup/provision_dns_add_samba.ldif
/usr/share/samba/setup/provision_dnszones_add.ldif
/usr/share/samba/setup/provision_dnszones_modify.ldif
/usr/share/samba/setup/provision_dnszones_partitions.ldif
/usr/share/samba/setup/provision_group_policy.ldif
/usr/share/samba/setup/provision_init.ldif
/usr/share/samba/setup/provision_partitions.ldif
/usr/share/samba/setup/provision_privilege.ldif
/usr/share/samba/setup/provision_rootdse_add.ldif
/usr/share/samba/setup/provision_rootdse_modify.ldif
/usr/share/samba/setup/provision_schema_basedn.ldif
/usr/share/samba/setup/provision_schema_basedn_modify.ldif
/usr/share/samba/setup/provision_self_join.ldif
/usr/share/samba/setup/provision_self_join_config.ldif
/usr/share/samba/setup/provision_self_join_modify.ldif
/usr/share/samba/setup/provision_self_join_modify_config.ldif
/usr/share/samba/setup/provision_users.ldif
/usr/share/samba/setup/provision_users_add.ldif
/usr/share/samba/setup/provision_users_modify.ldif
/usr/share/samba/setup/provision_well_known_sec_princ.ldif
/usr/share/samba/setup/refint.conf
/usr/share/samba/setup/schema-map-fedora-ds-1.0
/usr/share/samba/setup/schema-map-openldap-2.3
/usr/share/samba/setup/schema_samba4.ldif
/usr/share/samba/setup/secrets.ldif
/usr/share/samba/setup/secrets_dns.ldif
/usr/share/samba/setup/secrets_init.ldif
/usr/share/samba/setup/secrets_sasl_ldap.ldif
/usr/share/samba/setup/secrets_simple_ldap.ldif
/usr/share/samba/setup/share.ldif
/usr/share/samba/setup/slapd.conf
/usr/share/samba/setup/spn_update_list
/usr/share/samba/setup/ypServ30.ldif"

puts "[?] Applications size (i386): "
puts "[1] Apache2 : Verions 2.4.7-1ubuntu4.20               | Package Size 85.5 kB      | Installed Size 464.0 kB"
puts "[2] Vsftpd  : Verions -                               | Package Size 112.0 kB	  | Installed Size 363.0 kB"
puts "[3] Samba   : Verions 2:4.3.11+dfsg-0ubuntu0.14.04.19 | Package Size 886.9 kB	  | Installed Size 11,238.0 kB"
puts 

puts "[?] Total Files (i386):"
puts "[1] Apache2 => " + apache.split("\n").count.to_s + " files"
puts "[2] Vsftpd  => " + vsftpd.split("\n").count.to_s + " files"
puts "[3] Samba   => " + samba.split("\n").count.to_s + " files"
